export interface Opportunity {
  id: string;
  title: string;
  company: string;
  companyId: string;
  location: string;
  type: "internship" | "full-time" | "part-time" | "project" | "mentorship";
  requiredSkills: string[];
  preferredSkills: string[];
  matchScore: number;
  status: "active" | "closing-soon" | "draft" | "closed";
  postedAt: string;
  deadline: string;
  stipend?: string;
  salary?: string;
  remote: boolean;
  description: string;
  responsibilities: string[];
  requirements: string[];
  benefits: string[];
  duration?: string;
  applicants: number;
}

export const mockOpportunities: Opportunity[] = [
  {
    id: "1",
    title: "Frontend Developer Intern",
    company: "TechCorp India",
    companyId: "c1",
    location: "Bangalore",
    type: "internship",
    requiredSkills: ["React", "TypeScript", "HTML/CSS"],
    preferredSkills: ["Tailwind CSS", "Git"],
    matchScore: 87,
    status: "active",
    postedAt: "2026-09-15",
    deadline: "2026-10-15",
    stipend: "15,000/month",
    remote: false,
    description: "Join our frontend team to build cutting-edge web applications using React and TypeScript.",
    responsibilities: ["Build responsive UI components", "Write clean TypeScript code", "Participate in code reviews", "Collaborate with designers"],
    requirements: ["Strong React fundamentals", "TypeScript knowledge", "Understanding of HTML/CSS"],
    benefits: ["Mentorship", "Certificate", "PPO opportunity"],
    duration: "6 months",
    applicants: 45,
  },
  {
    id: "2",
    title: "Full Stack Engineer",
    company: "StartupXYZ",
    companyId: "c2",
    location: "Remote",
    type: "full-time",
    requiredSkills: ["React", "Node.js", "PostgreSQL"],
    preferredSkills: ["Docker", "AWS", "GraphQL"],
    matchScore: 73,
    status: "active",
    postedAt: "2026-09-10",
    deadline: "2026-10-30",
    salary: "8-12 LPA",
    remote: true,
    description: "Build scalable full-stack applications for our growing platform.",
    responsibilities: ["Develop frontend and backend features", "Design REST APIs", "Manage database schemas", "Deploy to cloud"],
    requirements: ["2+ years experience", "React and Node.js proficiency", "Database experience"],
    benefits: ["Remote work", "Flexible hours", "Stock options"],
    applicants: 32,
  },
  {
    id: "3",
    title: "React Developer",
    company: "WebAgency",
    companyId: "c3",
    location: "Mumbai",
    type: "full-time",
    requiredSkills: ["React", "JavaScript", "CSS"],
    preferredSkills: ["Next.js", "Figma"],
    matchScore: 68,
    status: "active",
    postedAt: "2026-09-12",
    deadline: "2026-10-20",
    salary: "6-10 LPA",
    remote: false,
    description: "Create beautiful, performant web interfaces for our clients.",
    responsibilities: ["Build React applications", "Implement responsive designs", "Optimize performance"],
    requirements: ["1+ year React experience", "Strong CSS skills", "Eye for design"],
    benefits: ["Learning opportunities", "Team events", "Health insurance"],
    applicants: 28,
  },
  {
    id: "4",
    title: "Cloud Engineering Intern",
    company: "CloudFirst",
    companyId: "c4",
    location: "Hyderabad",
    type: "internship",
    requiredSkills: ["AWS", "Linux", "Networking"],
    preferredSkills: ["Docker", "Kubernetes", "Terraform"],
    matchScore: 42,
    status: "active",
    postedAt: "2026-09-08",
    deadline: "2026-10-10",
    stipend: "12,000/month",
    remote: false,
    description: "Learn cloud infrastructure and DevOps practices from industry experts.",
    responsibilities: ["Assist in cloud deployments", "Monitor infrastructure", "Write documentation"],
    requirements: ["Basic Linux knowledge", "Interest in cloud computing"],
    benefits: [" hands-on experience", "Certification support", "Mentorship"],
    duration: "3 months",
    applicants: 18,
  },
  {
    id: "5",
    title: "Data Science Intern",
    company: "DataLab",
    companyId: "c5",
    location: "Delhi",
    type: "internship",
    requiredSkills: ["Python", "SQL", "Data Analysis"],
    preferredSkills: ["Machine Learning", "Pandas", "TensorFlow"],
    matchScore: 55,
    status: "closing-soon",
    postedAt: "2026-09-05",
    deadline: "2026-09-25",
    stipend: "18,000/month",
    remote: false,
    description: "Work on real data science projects and learn ML fundamentals.",
    responsibilities: ["Analyze datasets", "Build ML models", "Create visualizations"],
    requirements: ["Python proficiency", "Statistics basics", "SQL knowledge"],
    benefits: ["Portfolio projects", "Recommendation letter", "PPO opportunity"],
    duration: "6 months",
    applicants: 52,
  },
  {
    id: "6",
    title: "Backend Developer",
    company: "CodeStudio",
    companyId: "c6",
    location: "Pune",
    type: "full-time",
    requiredSkills: ["Node.js", "REST APIs", "PostgreSQL"],
    preferredSkills: ["Redis", "Docker", "Microservices"],
    matchScore: 61,
    status: "active",
    postedAt: "2026-09-14",
    deadline: "2026-10-14",
    salary: "7-11 LPA",
    remote: false,
    description: "Build robust backend systems for our SaaS platform.",
    responsibilities: ["Design APIs", "Optimize databases", "Write tests", "Handle deployments"],
    requirements: ["Node.js expertise", "API design skills", "Database optimization"],
    benefits: ["Competitive salary", "Learning budget", "Flexible PTO"],
    applicants: 24,
  },
  {
    id: "7",
    title: "UI/UX Design Intern",
    company: "InnovateTech",
    companyId: "c7",
    location: "Bangalore",
    type: "internship",
    requiredSkills: ["Figma", "HTML/CSS", "Design Systems"],
    preferredSkills: ["Prototyping", "User Research"],
    matchScore: 48,
    status: "active",
    postedAt: "2026-09-11",
    deadline: "2026-10-11",
    stipend: "10,000/month",
    remote: true,
    description: "Design beautiful user experiences for our mobile and web products.",
    responsibilities: ["Create wireframes and prototypes", "Conduct user research", "Build design components"],
    requirements: ["Figma proficiency", "Design portfolio", "Understanding of UX principles"],
    benefits: ["Portfolio building", "Mentorship", "Remote work"],
    duration: "4 months",
    applicants: 38,
  },
  {
    id: "8",
    title: "Mentor - Web Development",
    company: "EduStack",
    companyId: "c8",
    location: "Remote",
    type: "mentorship",
    requiredSkills: ["React", "Node.js", "Git"],
    preferredSkills: ["Teaching", "Communication"],
    matchScore: 78,
    status: "active",
    postedAt: "2026-09-13",
    deadline: "2026-11-01",
    remote: true,
    description: "Guide students in their web development journey through 1-on-1 mentorship.",
    responsibilities: ["Weekly 1-hour sessions", "Code reviews", "Career guidance", "Project feedback"],
    requirements: ["3+ years experience", "Strong communication skills", "Patience"],
    benefits: ["Give back to community", "Network with students", "Flexible schedule"],
    applicants: 15,
  },
];

export const mockOpportunityCategories = [
  { id: "1", name: "Internships", count: 4, icon: "briefcase" },
  { id: "2", name: "Full-time Jobs", count: 3, icon: "building" },
  { id: "3", name: "Mentorship", count: 1, icon: "users" },
  { id: "4", name: "Projects", count: 0, icon: "folder" },
  { id: "5", name: "Workshops", count: 0, icon: "academic" },
  { id: "6", name: "Challenges", count: 0, icon: "trophy" },
];
